### ISSUE TITLE
Broken Avatar Decoration Alignment

### ISSUE THREAD

**Issue by WeeScottishMan** [qt-kaneko/Chat-Bubbles#2]
Discord recently released a feature that added avatar decorations and this caused an issue with chat bubbles as seen below.

![Screenshot_20221213_063242](https://user-images.githubusercontent.com/85060818/207416377-028172ed-8743-4096-99ab-3b7b0bc3893a.png)

I fixed this by adding some code that realigned the decoration and fixed the alignment in replies too as seen here.

![Screenshot_20221213_072912](https://user-images.githubusercontent.com/85060818/207427055-68667c60-eac3-434a-9178-269c9e1a147e.png)

**Code used**
`.avatarDecoration-34OC0G {  /* Aligns avatar decoration to avatar */
  margin-left: -4.6rem;
  margin-top: -0.2rem;
}

.repliedMessage-3Z6XBG + .contents-2MsGLg > .avatarDecoration-34OC0G { /* Set avatar decoration position near answer message */
  margin-top: -45px;
}`

Adding this issue so it will hopefully be fixed on the main repository and for a new release to come out. Thank you for the theme it's very cool hope this contributes to helping the theme improve 😄

_Sorry if this is the wrong place to put this I don't know github too well_

**Comment by qt-kaneko** [comment]
Thank you a lot. Successfully fixed 👍
